name = "PowerModelsStability"
uuid = "f9e4c324-c3b6-4bca-9c3d-419775f0bd17"
authors = ["Haoxiang Yang", "David M Fobes <dfobes@lanl.gov>"]
repo = "https://github.com/lanl-ansi/PowerModelsStability.jl.git"
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
Ipopt = ">= 0.4"
PowerModelsDistribution = "~0.9"
julia = "^1"

[extras]
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
PowerModelsDistribution = "d7431456-977f-11e9-2de3-97ff7677985e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Ipopt", "PowerModelsDistribution", "Test"]
